server:
  port: 8090

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Git 仓库的地址
          uri: https://github.com/1019509861/spring_cloud_summary/
          # 仓库下配置文件的路径
          search-paths: config
          # 公有仓库可不写账户密码，私有则需要
          username:
          password:
          # basedir: 可以写本地仓库的地址，如 E:\project\
      # 使用的仓库分支
      label: master
    # 追踪配置
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
# 注册到 Eureka 服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8081/eureka
# 暴露刷新端点
management:
  endpoints:
    web:
      exposure:
        include: "*"