server:
  port: 8868

spring:
  cloud:
    nacos:
      discovery:
#        server-addr: 119.91.138.217:8848 # nacos 服务端地址
        cluster-name: GZ                  # 指定服务所在集群
#        namespace: 54d6ef39-0142-4881-be78-db62d05a78f6  # 指定服务所属命名空间 ID，默认是 public
        group: localhost                  # 指定服务实例所在分组
        ephemeral: true                   # 指定当前服务实例为永久实例，默认 true（临时实例）

# 指定服务负载均衡策略
nacos-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule