spring:
  application:
    name: zipkin-client-two
  zipkin:
    base-url: http://localhost:9411   # Zipkin Server 地址
  sleuth:
    sampler:
      probability: 1.0  # 表示数据采集比例，介于 0.0 ~ 1.0
server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8081/eureka/

