server:
  port: 8081

spring:
  application:
    name: eureka-server
  # 设置安全认证用户名
  security:
    user:
      name: admin
      password: admin123

eureka:
#  server:
  # 关闭服务保护功能
  #  enable-self-preservation: false
  # 服务清除间隔（毫秒），服务心跳失效多久后删除，
  #  eviction-interval-timer-in-ms: 60000
  # Eureka 服务器 IP 地址
  instance:
    hostname: localhost
  client:
    # 是否将自己的信息注册到 Eureka 服务器上供其它服务发现，默认 true
    register-with-eureka: false
    # 当前实例是否获取 Eureka 服务器上注册表的注册信息（即服务），默认 true
    fetch-registry: false
    service-url:
      defualtZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8081/eureka
#spring:
#  profiles:
#    active: peer1
