server:
  port: 8082

spring:
  application:
    name: client-one
  cloud:
    zookeeper:
      # 连接到 zookeeper
      connect-string: localhost:2181
# eureka 配置
  #eureka:
#  client:
    # 表示服务要注册到哪个注册中心，默认是 http://IP:Port/eureka/
#    service-url:
#      defaultZone: http://admin:admin123@localhost:8081/eureka
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"